name: smartstruct_example
description: example
version: 1.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  freezed_annotation: ^1.1.0
  injectable: ^1.5.3
  smartstruct: ^1.2.6
dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  #smartstruct_generator: ^1.2.6
  smartstruct_generator:
    path: ../generator
dependency_overrides:
  smartstruct:
    path: ../smartstruct
