name: smartstruct
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.4.0
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
dependencies: null
